service: line-otayori-photo

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: ap-northeast-1
  profile: serverless-admin

functions:
  lineWebhook:
    handler: handler.lineWebhook
    events:
      - http:
          path: line/webhook
          method: post
    timeout: 30

plugins:
  - serverless-offline
